// This file is automatically generated - edits will be lost!
'use server';

/**
 * @fileOverview Uses Gemini Vision to scan and identify a TCG card's name, set, rarity, and game.
 *
 * - scanTCGCard - A function that handles the card scanning process.
 * - ScanTCGCardInput - The input type for the scanTCGCard function.
 * - ScanTCGCardOutput - The return type for the scanTCGCard function.
 */

import {ai, createUserAI} from '@/ai/genkit';
import {z} from 'genkit';
import type { TCGGame } from '@/types';

const ScanTCGCardInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a trading card, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  userId: z.string().describe("The user ID for personalized API key usage.").optional(),
  game: z.enum(['pokemon', 'onepiece', 'lorcana', 'magic', 'dragonball']).optional().describe("The TCG game to scan for. If not specified, will auto-detect."),
});
export type ScanTCGCardInput = z.infer<typeof ScanTCGCardInputSchema>;

const ScanTCGCardOutputSchema = z.object({
  cardDetails: z.object({
    name: z.string().describe("The name of the card.").optional(),
    set: z.string().describe("The set the card belongs to.").optional(),
    rarity: z.string().describe("The rarity of the card.").optional(),
    game: z.enum(['pokemon', 'onepiece', 'lorcana', 'magic', 'dragonball']).describe("The TCG game this card is from.").optional(),
  }).describe("Details about the trading card.").optional(),
  error: z.string().describe("Error message if the card could not be identified.").optional()
});

export type ScanTCGCardOutput = z.infer<typeof ScanTCGCardOutputSchema>;

export async function scanTCGCard(input: ScanTCGCardInput): Promise<ScanTCGCardOutput> {
  return scanTCGCardFlow(input);
}

async function createScanPromptAndFlow(userAI: any) {
  const gameHint = (game?: string) => {
    if (!game) return "First, identify which trading card game this is from (Pokémon, One Piece, Lorcana, Magic: The Gathering, or Dragon Ball).";
    const gameNames = {
      pokemon: 'Pokémon TCG',
      onepiece: 'One Piece Card Game',
      lorcana: 'Disney Lorcana',
      magic: 'Magic: The Gathering',
      dragonball: 'Dragon Ball Super Card Game'
    };
    return `This is a ${gameNames[game as keyof typeof gameNames]} card.`;
  };

  const scanTCGCardPrompt = userAI.definePrompt({
    name: 'scanTCGCardPrompt',
    input: {schema: ScanTCGCardInputSchema},
    output: {schema: ScanTCGCardOutputSchema},
    prompt: `You are an expert trading card game appraiser with deep knowledge of Pokémon TCG, One Piece Card Game, Disney Lorcana, Magic: The Gathering, and Dragon Ball Super Card Game.
    
{{#if game}}
${gameHint('{{game}}')}
{{else}}
${gameHint()}
{{/if}}

Use the following image to identify:
1. The card's name
2. The set it belongs to
3. The rarity
4. The game (if not already specified)

Photo: {{media url=photoDataUri}}

Respond using the following format:
{
  "cardDetails": {
    "name": "Card name",
    "set": "Set name or expansion",
    "rarity": "Card rarity",
    "game": "pokemon" | "onepiece" | "lorcana" | "magic" | "dragonball"
  }
}

If you cannot identify the card or if the image does not contain a trading card, respond with:
{
  "error": "Error message describing why the card could not be identified"
}`,
  });

  const scanTCGCardFlow = userAI.defineFlow(
    {
      name: 'scanTCGCardFlow',
      inputSchema: ScanTCGCardInputSchema,
      outputSchema: ScanTCGCardOutputSchema,
    },
    async (input: ScanTCGCardInput) => {
      try {
        const {output} = await scanTCGCardPrompt(input);
        return output!;
      } catch (error: any) {
        console.error('Error during card scanning:', error);
        return {error: 'Failed to scan trading card.'};
      }
    }
  );

  return scanTCGCardFlow;
}

const scanTCGCardFlow = ai.defineFlow(
  {
    name: 'scanTCGCardFlow',
    inputSchema: ScanTCGCardInputSchema,
    outputSchema: ScanTCGCardOutputSchema,
  },
  async (input: ScanTCGCardInput) => {
    try {
      const userAI = await createUserAI(input.userId || '');
      const flow = await createScanPromptAndFlow(userAI);
      return await flow(input);
    } catch (error: any) {
      console.error('Error during card scanning:', error);
      return {error: 'Failed to scan trading card.'};
    }
  }
);
